:verbose: true
:concurrency: 1
:pidfile: tmp/pids/sidekiq-0.pid
:logfile: ./log/sidekiq.log
:timeout: 300
:queues:
  - [high_priority, 20]
  - [default, 10]
  - [mailers, 5]
  - [low_priority, 2]
  - [active_storage_analysis, 1]
  - [active_storage_purge, 1]
staging:
  :concurrency: 5
validation:
  :concurrency: 5
production:
  :concurrency: 5
